// Generated by gencpp from file sauvc/toggle_switch_formRequest.msg
// DO NOT EDIT!


#ifndef SAUVC_MESSAGE_TOGGLE_SWITCH_FORMREQUEST_H
#define SAUVC_MESSAGE_TOGGLE_SWITCH_FORMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sauvc
{
template <class ContainerAllocator>
struct toggle_switch_formRequest_
{
  typedef toggle_switch_formRequest_<ContainerAllocator> Type;

  toggle_switch_formRequest_()
    : data(false)  {
    }
  toggle_switch_formRequest_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> const> ConstPtr;

}; // struct toggle_switch_formRequest_

typedef ::sauvc::toggle_switch_formRequest_<std::allocator<void> > toggle_switch_formRequest;

typedef boost::shared_ptr< ::sauvc::toggle_switch_formRequest > toggle_switch_formRequestPtr;
typedef boost::shared_ptr< ::sauvc::toggle_switch_formRequest const> toggle_switch_formRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sauvc::toggle_switch_formRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sauvc::toggle_switch_formRequest_<ContainerAllocator1> & lhs, const ::sauvc::toggle_switch_formRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sauvc::toggle_switch_formRequest_<ContainerAllocator1> & lhs, const ::sauvc::toggle_switch_formRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sauvc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::sauvc::toggle_switch_formRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sauvc/toggle_switch_formRequest";
  }

  static const char* value(const ::sauvc::toggle_switch_formRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n"
;
  }

  static const char* value(const ::sauvc::toggle_switch_formRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct toggle_switch_formRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sauvc::toggle_switch_formRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sauvc::toggle_switch_formRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAUVC_MESSAGE_TOGGLE_SWITCH_FORMREQUEST_H
