// Generated by gencpp from file sauvc/toggle_switch_formResponse.msg
// DO NOT EDIT!


#ifndef SAUVC_MESSAGE_TOGGLE_SWITCH_FORMRESPONSE_H
#define SAUVC_MESSAGE_TOGGLE_SWITCH_FORMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sauvc
{
template <class ContainerAllocator>
struct toggle_switch_formResponse_
{
  typedef toggle_switch_formResponse_<ContainerAllocator> Type;

  toggle_switch_formResponse_()
    : result(false)
    , message()  {
    }
  toggle_switch_formResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> const> ConstPtr;

}; // struct toggle_switch_formResponse_

typedef ::sauvc::toggle_switch_formResponse_<std::allocator<void> > toggle_switch_formResponse;

typedef boost::shared_ptr< ::sauvc::toggle_switch_formResponse > toggle_switch_formResponsePtr;
typedef boost::shared_ptr< ::sauvc::toggle_switch_formResponse const> toggle_switch_formResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sauvc::toggle_switch_formResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sauvc::toggle_switch_formResponse_<ContainerAllocator1> & lhs, const ::sauvc::toggle_switch_formResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sauvc::toggle_switch_formResponse_<ContainerAllocator1> & lhs, const ::sauvc::toggle_switch_formResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sauvc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b543fbd3518c791be28589b850702201";
  }

  static const char* value(const ::sauvc::toggle_switch_formResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb543fbd3518c791bULL;
  static const uint64_t static_value2 = 0xe28589b850702201ULL;
};

template<class ContainerAllocator>
struct DataType< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sauvc/toggle_switch_formResponse";
  }

  static const char* value(const ::sauvc::toggle_switch_formResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::sauvc::toggle_switch_formResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct toggle_switch_formResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sauvc::toggle_switch_formResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sauvc::toggle_switch_formResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAUVC_MESSAGE_TOGGLE_SWITCH_FORMRESPONSE_H
