(cl:defpackage sauvc-srv
  (:use )
  (:export
   "TOGGLE_SWITCH_FORM"
   "<TOGGLE_SWITCH_FORM-REQUEST>"
   "TOGGLE_SWITCH_FORM-REQUEST"
   "<TOGGLE_SWITCH_FORM-RESPONSE>"
   "TOGGLE_SWITCH_FORM-RESPONSE"
  ))

